# Site
name: "The Mindlab"
title: "The Mindlab"
description: "Jekyll Theme for Blogging"
meta_description: "Jekyll theme for blogging."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/mindlab'
email: 'romaspace@gmail.com'
google_analytics: ''
disqus: ''
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  roma:
    name: Roma Sharma
    display_name: Roma
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: romaspace@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/romasharma
    facebook: https://www.facebook.com/themindlabtraining/
    google: https://business.google.com/dashboard/l/17278415145324209822?hl=en-GB
    description: "Life Coach certified in person-centered therapy, with a background in Transactional Analysis, Neuro Linguistic Programming and Hypnotic Communication Skills."

testimonials:
  -
    name: Rajeshwari, Bank Employee
    quote: Roma has excellent communication skills and she made the session enjoyable with her deep understanding of the subject and subtle sense of humour. My perspective about the way I look at things has changed for the better and only a person who teaches with passion for the subject will be able to make such a profound influence.
  -
    name: Rachana Ghatol Shetty, Reiki Master
    quote: The foundation workshop on NLP was a wonderfully articulated program. Roma is an excellent trainer and there were many positive take aways from the program to be used in our personal n professional lives. Highly recommended for everyone seeking a positive insight.
  -
    name: Bharath Chandrashekhar, Software Engineer
    quote: Best course by the best trainer. The program is very informative and gives us a ladder to achieve goals. Roma is an amazing trainer . She is very friendly , very knowledgeable and makes the session very interesting and entertaining. Very memorable experience.

gallery:
  - 1.png
  - 2.png
  - 3.png
  - 3.png
  - 3.png
  - 3.png
  - 3.png
  - 3.png
  - 2.png

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
